# ALGORITHM TO REMOVE DUPLICATES FROM LIST
''' WE CAN USE HASH TABLE TO CHECK WHETHER THE ELEMENT IS REPEATING OR NOT. IF THE ELEMENT IS NOT IN HASH TABLE, THEN INSERT IT IN HASH TABLE. KEEP ON INSERTING THE ELEMENT, IF IT IS IN HASH TABLE, THEN SKIP THAT ELEMENT.
'''
# AUTHOR : PANKAJ KUMAR

r = [1,1,2,7,4,3,3,7,9]
l = []
s = set()
for e in r:
    if e not in s:
        l.append(e)
        s.add(e)
print l
        
#OUTPUT: [1,2,7,4,3,9]
